In [22]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [10]:
df= pd.read_csv(r'C:\Users\pbann\OneDrive\Desktop\science\data set\fetal_health\train.csv')

In [11]:
df

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              142.0          0.000           0.000                 0.007   
1              122.0          0.000           0.000                 0.006   
2              129.0          0.005           0.003                 0.001   
3              136.0          0.006           0.000                 0.008   
4              144.0          0.000           0.000                 0.006   
...              ...            ...             ...                   ...   
1695           129.0          0.000           0.001                 0.006   
1696           142.0          0.001           0.003                 0.001   
1697           147.0          0.013           0.000                 0.010   
1698           130.0          0.003           0.000                 0.007   
1699           123.0          0.004           0.007                 0.000   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                     0.000   
1                   0.002                   0.0                     0.000   
2                   0.000                   0.0                     0.000   
3                   0.000                   0.0                     0.000   
4                   0.000                   0.0                     0.000   
...                   ...                   ...                       ...   
1695                0.008                   0.0                     0.002   
1696                0.002                   0.0                     0.000   
1697                0.000                   0.0                     0.000   
1698                0.000                   0.0                     0.000   
1699                0.000                   0.0                     0.000   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                58.0                                   0.4   
1                                27.0                                   1.4   
2                                34.0                                   1.7   
3                                45.0                                   0.8   
4                                32.0                                   1.0   
...                               ...                                   ...   
1695                             65.0                                   2.8   
1696                             55.0                                   1.3   
1697                             36.0                                   1.2   
1698                             33.0                                   1.1   
1699                             56.0                                   0.7   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                   9.0       ...   
1                                                   4.0       ...   
2                                                   0.0       ...   
3                                                   2.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
1695                                                0.0       ...   
1696                                               10.0       ...   
1697                                                0.0       ...   
1698                                                0.0       ...   
1699                                                0.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
0             136.0          156.0                        0.0   
1              91.0          144.0                        4.0   
2              78.0          196.0                       10.0   
3             129.0          158.0                        2.0   
4             122.0          160.0                   

In [14]:
X=df.drop('fetal_health',axis=1)
Y=df['fetal_health']

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X=scaler.fit_transform(X)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y)

In [24]:
rfc=RandomForestClassifier()

In [26]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [32]:
predict =rfc.predict(x_test)
predict

array([1., 3., 1., 1., 2., 2., 1., 1., 2., 1., 1., 3., 3., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 2., 1., 1., 3., 1.,
       1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       1., 1., 1., 1., 3., 2., 3., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       2., 1., 2., 1., 1., 3., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 2.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 3., 1., 1., 1., 3., 2., 1., 1.,
       1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 1., 1.,
       3., 1., 1., 1., 1., 3., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 3., 2., 1.

In [31]:
accuracy_score(y_test,predict)

0.96

In [25]:
from sklearn.svm import LinearSVC

model = LinearSVC(loss='hinge', dual=True)
model.fit(x_train, y_train)

C:\Users\pbann\Anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(loss='hinge')

In [18]:
from sklearn.svm import LinearSVC

model = LinearSVC(loss='hinge', dual=True)
model.fit(x_train, y_train)
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))

--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.95      0.94      0.95       998
         2.0       0.69      0.65      0.67       193
         3.0       0.73      0.90      0.81        84

    accuracy                           0.90      1275
   macro avg       0.79      0.83      0.81      1275
weighted avg       0.90      0.90      0.90      1275

------------------      Accuracy      --------- = 0.8956862745098039
CONFUSION MATRIX
[[940  52   6]
 [ 45 126  22]
 [  3   5  76]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.96      0.95      0.95       336
         2

C:\Users\pbann\Anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [19]:
from sklearn import svm
from sklearn.svm import LinearSVC
model = svm.SVC(kernel='poly', degree=3.7, gamma='auto', coef0=1, C=5)
model.fit(x_train,y_train)
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))

--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.97      0.98       994
         2.0       0.84      0.87      0.85       178
         3.0       0.95      0.96      0.96       103

    accuracy                           0.96      1275
   macro avg       0.92      0.93      0.93      1275
weighted avg       0.96      0.96      0.96      1275

------------------      Accuracy      --------- = 0.9584313725490196
CONFUSION MATRIX
[[969  25   0]
 [ 19 154   5]
 [  0   4  99]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.96      0.97       340
         2

In [20]:
model = svm.SVC(kernel='rbf', gamma='auto', C=9)
model.fit(x_train, y_train)
print("--------------------------------------------Training Insights-----------------------------------------------------------")
pred=model.predict(x_train)
print(classification_report(pred,y_train))
Accuracy= accuracy_score(pred,y_train)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_train))
print("--------------------------------------------------------------------------------------------------------------------------")
print("--------------------------------------------Testing Insights---------------------------------------------------------------")
pred=model.predict(x_test)
print(classification_report(pred,y_test))
Accuracy= accuracy_score(pred,y_test)
print("------------------      Accuracy      --------- =",Accuracy)
print("CONFUSION MATRIX")
print(confusion_matrix(pred,y_test))

--------------------------------------------Training Insights-----------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.97      0.98       995
         2.0       0.85      0.86      0.85       181
         3.0       0.93      0.98      0.96        99

    accuracy                           0.96      1275
   macro avg       0.92      0.94      0.93      1275
weighted avg       0.96      0.96      0.96      1275

------------------      Accuracy      --------- = 0.9576470588235294
CONFUSION MATRIX
[[969  26   0]
 [ 19 155   7]
 [  0   2  97]]
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------Testing Insights---------------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.98      0.96      0.97       340
         2