In [5]:
import pandas as pd
import numpy as np


In [3]:
A = np.array([[3,7],
         [-4,-6],
         [7,8],
          [1,-1],
          [-4,-1],
          [-3,-7]
          ])

In [4]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [6]:
A.shape

(6, 2)

In [10]:
#check wether my data in standard scaler:
df=pd.DataFrame(A,columns=['a0','a1'])

In [11]:
df.describe()

a0        a1
count  6.000000  6.000000
mean   0.000000  0.000000
std    4.472136  6.324555
min   -4.000000 -7.000000
25%   -3.750000 -4.750000
50%   -1.000000 -1.000000
75%    2.500000  5.000000
max    7.000000  8.000000

# tofind relation b/w two features covariance of two columns=

In [12]:
df.corr()

a0        a1
a0  1.000000  0.883883
a1  0.883883  1.000000

In [13]:
a0=A[:,0]
a1=A[:,1]

In [15]:
np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [17]:
np.sum(a0*a1)/5    # mean =0

25.0

In [22]:
A.T

array([[ 3, -4,  7,  1, -4, -3],
       [ 7, -6,  8, -1, -1, -7]])

In [24]:
sigma =A.T@A/5

In [26]:
l,x=np.linalg.eig(sigma)

In [27]:
l

array([ 3.07417596, 56.92582404])

In [28]:
sigma

array([[20., 25.],
       [25., 40.]])

In [29]:
sigma@x[:,0]

array([-2.54562438,  1.72347161])

In [30]:
sigma@x[:,1]

array([-31.91425695, -47.13840945])

In [36]:
print('1st principal component','second')
x[:,0]


1st principal component second


array([-0.82806723,  0.56062881])

In [37]:
x[:,1]

array([-0.56062881, -0.82806723])

In [38]:
pc1_arr=A@x[:,1]

In [39]:
pc2_arr=A@x[:,0]

In [40]:
pc1_arr

array([ -7.47835704,   7.21091862, -10.54893951,   0.26743842,
         3.07058247,   7.47835704])

In [41]:
pc2_arr

array([ 1.44019997, -0.05150393, -1.31144014, -1.38869604,  2.75164011,
       -1.44019997])

In [49]:
df=pd.read_csv(r'C:/Users/pbann/OneDrive/Desktop/science/glass.csv')

In [52]:
df=df.drop(columns=['Type'],axis=1)

KeyError: "['Type'] not found in axis"

In [54]:
df.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe  
count  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009  
std      1.423153    0.497219    0.097439  
min      5.430000    0.000000    0.000000  
25%      8.240000    0.000000    0.000000  
50%      8.600000    0.000000    0.000000  
75%      9.172500    0.000000    0.100000  
max     16.190000    3.150000    0.510000

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled=scaler.fit_transform(df)

In [59]:
df1=pd.DataFrame(df_scaled)

In [60]:
df1.describe()

0             1             2             3             4  \
count  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02   
mean  -2.877449e-14  2.179980e-15 -2.801497e-16 -3.434428e-16  9.966067e-16   
std    1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00   
min   -2.381516e+00 -3.286943e+00 -1.865511e+00 -2.318616e+00 -3.676472e+00   
25%   -6.082728e-01 -6.141580e-01 -3.957744e-01 -5.117560e-01 -4.800288e-01   
50%   -2.262293e-01 -1.323817e-01  5.527787e-01 -1.704602e-01  1.799655e-01   
75%    2.614331e-01  5.120326e-01  6.361680e-01  3.715977e-01  5.649621e-01   
max    5.137232e+00  4.875637e+00  1.254639e+00  4.125851e+00  3.570524e+00   

                  5             6             7             8  
count  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02  
mean   7.470660e-17 -3.137418e-16 -1.763906e-16 -6.121791e-17  
std    1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00  
min   -7.639186e-01 -2.484084e+00 -3.528768e-01 -5.864509e-01  
25%   -5.756501e-01 -5.049657e-01 -3.528768e-01 -5.864509e-01  
50%    8.905322e-02 -2.514132e-01 -3.528768e-01 -5.864509e-01  
75%    1.735820e-01  1.518057e-01 -3.528768e-01  4.422417e-01  
max    8.780145e+00  5.094318e+00  5.997210e+00  4.659881e+00

In [62]:
sigma=np.cov(df_scaled)

In [63]:
l,x=np.linalg.eig(sigma)